// Base de datos de videos
const mediaDB = [
  {
    titulo: "Valeria Marquez",
    portada: "https://files.catbox.moe/slvfm7.png",
    video: "https://files.catbox.moe/1pkwcu.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "HDP usa el cuerpo de su amigo como escudo.",
    portada: "https://xxx.livegore.com//rb-include/videos/4641070840.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4641070840.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "En el show",
    portada: "https://files.catbox.moe/dt5026.png",
    video: "https://files.catbox.moe/ubdh0r.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Lo dejaron como lego",
    portada: "https://files.catbox.moe/td2vax.png",
    video: "https://files.catbox.moe/cqf1do.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Dj en la discoteca",
    portada: "https://files.catbox.moe/6x7mhl.png",
    video: "https://files.catbox.moe/6cj2ra.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Miss pacman version hombre",
    portada: "https://files.catbox.moe/vo5diu.png",
    video: "https://files.catbox.moe/n9qhmw.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Dulces sueños",
    portada: "https://files.catbox.moe/dg3ekz.png",
    video: "https://qu.ax/eAhz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ultra sicariato",
    portada: "https://files.catbox.moe/oherqd.png",
    video: "https://files.catbox.moe/luaidc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Debora Bessa",
    portada: "https://files.catbox.moe/7yjs4f.png",
    video: "https://files.catbox.moe/8kmz8o.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mejores amigas",
    portada: "https://files.catbox.moe/hsjdhw.png",
    video: "https://xxx.livegore.com//rb-include/videos/9147177832.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Niños acribillados",
    portada: "https://files.catbox.moe/70o082.png",
    video: "https://xxx.livegore.com//rb-include/videos/2778559220.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Cabo su propia tumba",
    portada: "https://files.catbox.moe/77wq57.png",
    video: "https://qu.ax/Xmxc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Terror en barberia",
    portada: "https://files.catbox.moe/c15ytq.png",
    video: "https://xxx.livegore.com//rb-include/videos/9372303844.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "5 segundos para correr",
    portada: "https://files.catbox.moe/vxgssg.png",
    video: "https://files.catbox.moe/s1urbp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El patron",
    portada: "https://files.catbox.moe/7fq07r.png",
    video: "https://files.catbox.moe/cyqbgr.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Negro en el suelo",
    portada: "https://files.catbox.moe/5a6eui.png",
    video: "https://xxx.livegore.com//rb-include/videos/407954896.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Funky Town",
    portada: "https://files.catbox.moe/wtk7g0.png",
    video: "https://files.catbox.moe/cwsb27.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Maria Fernanda Garcia Alvarez",
    portada: "https://files.catbox.moe/cn2qfa.png",
    video: "https://files.catbox.moe/4vx4ux.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Chupetica de lengua",
    portada: "https://files.catbox.moe/4nlmad.png",
    video: "https://files.catbox.moe/ayihdd.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Sicariato veloz",
    portada: "https://files.catbox.moe/8ljidh.png",
    video: "https://files.catbox.moe/zw8fzc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mayengg03",
    portada: "https://files.catbox.moe/q3qhpd.png",
    video: "https://qu.ax/hfzq.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Pastor e hijas",
    portada: "https://files.catbox.moe/2kmklg.png",
    video: "https://files.catbox.moe/cwu6r1.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mujer sin cabeza",
    portada: "https://files.catbox.moe/biadgn.png",
    video: "https://files.catbox.moe/20lf4e.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mientras tiene sexo",
    portada: "https://files.catbox.moe/qzu2t5.png",
    video: "https://xxx.livegore.com//rb-include/videos/8401789665.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El siri",
    portada: "https://files.catbox.moe/chsck2.png",
    video: "https://files.catbox.moe/atn1s6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Engañada",
    portada: "https://files.catbox.moe/dx6khw.png",
    video: "https://files.catbox.moe/idqeer.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Descuartizacion",
    portada: "https://files.catbox.moe/045rwa.png",
    video: "https://xxx.livegore.com//rb-include/videos/7525534546.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Delincuente es quemado vivo",
    portada: "https://files.catbox.moe/tiyz17.png",
    video: "https://files.catbox.moe/njpeeo.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Tiktok in Jamaica",
    portada: "https://files.catbox.moe/1fwu7h.png",
    video: "https://files.catbox.moe/ygc30v.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "13 mineros de pataz",
    portada: "https://files.catbox.moe/jl3861.png",
    video: "https://qu.ax/wgbNz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "No te duermas morena",
    portada: "https://files.catbox.moe/q9a05t.png",
    video: "https://forogore.net/data/video/1/1122-ce27403355895b0ceff4cc07a171fc40.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El mejor consejo",
    portada: "https://files.catbox.moe/qt9lpe.png",
    video: "https://files.catbox.moe/ks3clp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El pantera",
    portada: "https://files.catbox.moe/74rniv.png",
    video: "https://files.catbox.moe/p3a643.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Miss pacman",
    portada: "https://files.catbox.moe/ygjeay.png",
    video: "https://files.catbox.moe/z718ba.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Le mutilan la cabeza",
    portada: "https://files.catbox.moe/qsbobq.png",
    video: "https://files.catbox.moe/gozwd8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Por territorio",
    portada: "https://files.catbox.moe/ep3nbr.png",
    video: "https://files.catbox.moe/a8g01p.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ataque brutal",
    portada: "https://files.catbox.moe/8sdfmp.png",
    video: "https://xxx.livegore.com//rb-include/videos/3171774074.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mangue937",
    portada: "https://files.catbox.moe/x9qhwf.png",
    video: "https://files.catbox.moe/xjryj6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ejecucion con machete",
    portada: "https://files.catbox.moe/ogepdz.png",
    video: "https://files.catbox.moe/i2lva5.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "A 4 mujeres",
    portada: "https://files.catbox.moe/bba8b2.png",
    video: "https://files.catbox.moe/fdw9gg.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Cabeza con salsa de tomate",
    portada: "https://files.catbox.moe/ne9kng.png",
    video: "https://files.catbox.moe/zywytv.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Sadico en la banqueta",
    portada: "https://files.catbox.moe/7bn7wy.png",
    video: "https://files.catbox.moe/8i1yfc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Seicariato hogar",
    portada: "https://files.catbox.moe/eau99x.png",
    video: "https://files.catbox.moe/p5hvn8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Solo por 4 dolares",
    portada: "https://files.catbox.moe/kwrima.png",
    video: "https://files.catbox.moe/gxylxy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "No me pises pa",
    portada: "https://files.catbox.moe/3v7rxj.png",
    video: "https://files.catbox.moe/kb4d6i.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "QUIERO AGUA",
    portada: "https://files.catbox.moe/a2cw3r.png",
    video: "https://files.catbox.moe/l2lz6q.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Canservero",
    portada: "https://files.catbox.moe/sxc6qs.png",
    video: "https://files.catbox.moe/tfs5ma.mp4?f10k",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Patrocinado por adidas",
    portada: "https://files.catbox.moe/8448vs.png",
    video: "https://xxx.livegore.com//rb-include/videos/3258454720.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Fuente de sangre",
    portada: "https://files.catbox.moe/zqbhpt.png",
    video: "https://xxx.livegore.com//rb-include/videos/933355526.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "La matan frente a su hija",
    portada: "https://files.catbox.moe/3j7e9r.png",
    video: "https://files.catbox.moe/xprhs6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Hiper baleado",
    portada: "https://files.catbox.moe/p9cgnn.png",
    video: "https://files.catbox.moe/s65u0t.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mascara realista",
    portada: "https://files.catbox.moe/2ngo6p.png",
    video: "https://files.catbox.moe/pn0sa9.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "En el local",
    portada: "https://files.catbox.moe/826idb.png",
    video: "https://files.catbox.moe/m92oqa.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Su ultimo bailde",
    portada: "https://files.catbox.moe/tqqyhy.png",
    video: "https://video.wixstatic.com/video/031579_f812d4bbd85449ee988c082e5d2cd46c/480p/mp4/file.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mejor tirame un balazo",
    portada: "https://files.catbox.moe/wqc55i.png",
    video: "https://qu.ax/cZtn.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Amor de madre",
    portada: "https://files.catbox.moe/fw81p5.png",
    video: "https://files.catbox.moe/kvwgkk.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Los colgados",
    portada: "https://files.catbox.moe/5vlzgh.png",
    video: "https://xxx.livegore.com//rb-include/videos/2843126645.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Canibalismo",
    portada: "https://files.catbox.moe/b15tvr.png",
    video: "https://xxx.livegore.com//rb-include/videos/5890161800.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Te manda saludos",
    portada: "https://files.catbox.moe/qfew9j.png",
    video: "https://xxx.livegore.com//rb-include/videos/5660945787.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Niño asesina a su padre",
    portada: "https://files.catbox.moe/z61sbm.png",
    video: "https://files.catbox.moe/driisy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Lamentos de la muerte",
    portada: "https://files.catbox.moe/6trze4.png",
    video: "https://xxx.livegore.com//rb-include/videos/7094055935.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Hombre en el suelo",
    portada: "https://files.catbox.moe/5u1opj.png",
    video: "https://files.catbox.moe/8jnb2u.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El caso de kleber vieira 💀",
    portada: "https://files.catbox.moe/n40vtw.png",
    video: "https://files.catbox.moe/k95yws.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Asesinado sin piedad en Myanmar",
    portada: "https://xxx.livegore.com//rb-include/videos/5565926800.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5565926800.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "No mercy in Mexico",
    portada: "https://xxx.livegore.com//rb-include/videos/9235306940.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9235306940.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ghost Rider",
    portada: "https://xxx.livegore.com//rb-include/videos/954456399.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/954456399.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Se cree estaca", //C-ACCIDENTES
    portada: "https://files.catbox.moe/5jjfjq.png",
    video: "https://files.catbox.moe/7wqsp0.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Ancon ventanilla",
    portada: "https://files.catbox.moe/s430k9.png",
    video: "https://files.catbox.moe/rk1089.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "ACCIDENTE DE TRAFICO",
    portada: "https://files.catbox.moe/sc2hom.png",
    video: "https://files.catbox.moe/7w56bs.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Hombre puzzle",
    portada: "https://files.catbox.moe/pkxj7i.png",
    video: "https://xxx.livegore.com//rb-include/videos/7139274366.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Obulia Sanchez",
    portada: "https://files.catbox.moe/bznuaq.png",
    video: "https://xxx.livegore.com//rb-include/videos/1824291097.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "La grua",
    portada: "https://files.catbox.moe/ncn5dn.png",
    video: "https://files.catbox.moe/b2lw79.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Angelito caído del cielo",
    portada: "https://files.catbox.moe/dtuj10.png",
    video: "https://files.catbox.moe/jdo3f8.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Arrastrado por camion",
    portada: "https://files.catbox.moe/sbstuy.png",
    video: "https://files.catbox.moe/7rj3m0.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "A todo gas!",
    portada: "https://qu.ax/MpJRG.png",
    video: "https://files.catbox.moe/26p9hv.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "La division",
    portada: "https://qu.ax/tZdRP.png",
    video: "https://xxx.livegore.com//rb-include/videos/6121349534.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Extraño piercing",
    portada: "https://qu.ax/gdNBX.png",
    video: "https://files.catbox.moe/1kury2.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Policia erido",
    portada: "https://files.catbox.moe/ygeh1d.png",
    video: "https://files.catbox.moe/g5kv2o.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Volado",
    portada: "https://files.catbox.moe/kxv2zu.png",
    video: "https://files.catbox.moe/3j1103.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Camion asesino",
    portada: "https://files.catbox.moe/r61f3p.png",
    video: "https://files.catbox.moe/ggr14p.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Toro bravo",
    portada: "https://xxx.livegore.com//rb-include/videos/8443405479.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8443405479.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Tropeson",
    portada: "https://files.catbox.moe/knwbto.png",
    video: "https://files.catbox.moe/1504za.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Por jugar con pirotecnicos",
    portada: "https://files.catbox.moe/apxrh3.png",
    video: "https://files.catbox.moe/k8tikr.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Llanta explosiva",
    portada: "https://files.catbox.moe/vyyg7y.png",
    video: "https://files.catbox.moe/l5lilh.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Se la comio un tiburon",
    portada: "https://files.catbox.moe/fp2gmm.png",
    video: "https://xxx.livegore.com//rb-include/videos/7960827075.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Piquero se parte la cara",
    portada: "https://xxx.livegore.com//rb-include/videos/3819082602.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3819082602.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Sin la otra mitad",
    portada: "https://xxx.livegore.com//rb-include/videos/781994792.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/781994792.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "De un septimo piso",
    portada: "https://xxx.livegore.com//rb-include/videos/9534542048.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9534542048.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Por su motocicleta",
    portada: "https://xxx.livegore.com//rb-include/videos/8176755355.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8176755355.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Mortal en la piscina",
    portada: "https://xxx.livegore.com//rb-include/videos/5860242261.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5860242261.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Come la banqueta", //C-INCIDENTES
    portada: "https://files.catbox.moe/q7pgoy.png",
    video: "https://files.catbox.moe/hkxzb0.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Le corta sus partes",
    portada: "https://files.catbox.moe/mefoa3.png",
    video: "https://xxx.livegore.com//rb-include/videos/4989582831.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Las catrinas",
    portada: "https://files.catbox.moe/8cnbih.png",
    video: "https://xxx.livegore.com//rb-include/videos/8017226406.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "El frutero",
    portada: "https://files.catbox.moe/snwzh4.png",
    video: "https://files.catbox.moe/wlw7kh.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Pastor linchado por violar a su hija",
    portada: "https://files.catbox.moe/epr5aw.png",
    video: "https://files.catbox.moe/otbt2d.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "4 5 1 2 3",
    portada: "https://files.catbox.moe/ypk7ct.png",
    video: "https://files.catbox.moe/v23g8i.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Gresca de mujeres",
    portada: "https://files.catbox.moe/e80xzu.png",
    video: "https://files.catbox.moe/1307ww.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por bailar con su marido",
    portada: "https://files.catbox.moe/cohi27.png",
    video: "https://files.catbox.moe/il5khb.MP4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "La Billie Elish rusa",
    portada: "https://files.catbox.moe/m2iajh.png",
    video: "https://xxx.livegore.com//rb-include/videos/2504827566.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por matar a su bebe",
    portada: "https://files.catbox.moe/qr6i83.png",
    video: "https://files.catbox.moe/cmwlib.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Le amputan la oreja",
    portada: "https://files.catbox.moe/46b6a5.png",
    video: "https://files.catbox.moe/8fyuoi.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por burlase de su presentacion",
    portada: "https://files.catbox.moe/eezeto.png",
    video: "https://files.catbox.moe/s9ce2t.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "El futbolista",
    portada: "https://files.catbox.moe/mwzi22.png",
    video: "https://files.catbox.moe/delldy.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por robar",
    portada: "https://files.catbox.moe/3as0kv.png",
    video: "https://files.catbox.moe/prhxt5.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Valiente",
    portada: "https://files.catbox.moe/ib1n6g.png",
    video: "https://xxx.livegore.com//rb-include/videos/3146881824.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "tremendo golpe de chilenos ",
    portada: "https://files.catbox.moe/za8l90.png",
    video: "https://files.catbox.moe/7dm7ug.mp4",
    autor: "perritogore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Lo machetearon y cortazon la mano",
    portada: "https://files.catbox.moe/rl4qtc.png",
    video: "https://files.catbox.moe/r81nkv.mp4",
    autor: "perritogore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "No le robes a un narco mija",
    portada: "https://xxx.livegore.com//rb-include/videos/6842782353.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6842782353.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Los vagos 12",
    portada: "https://xxx.livegore.com//rb-include/videos/2281307470.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2281307470.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Martillazos en la cabeza",
    portada: "https://files.catbox.moe/fm3uku.png",
    video: "https://files.catbox.moe/cj1u5c.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "1444", //C-SUICIDIOS
    portada: "https://xxx.livegore.com//rb-include/videos/8122189044.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8122189044.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "India facebook",
    portada: "https://files.catbox.moe/pbnki8.png",
    video: "https://files.catbox.moe/nj8b9j.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "TRES DE LA MAÑANA EN BOLIVIA 💀",
    portada: "https://files.catbox.moe/7j2w3h.jpg",
    video: "https://files.catbox.moe/j6lqov.mp4",
    autor: "desconocido777",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Mujer Saltando De Su Apartamento En Rusia",
    portada: "https://xxx.livegore.com//rb-include/videos/4958379347.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4958379347.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Ultima llamada",
    portada: "https://files.catbox.moe/rx2a0o.png",
    video: "https://files.catbox.moe/jeggdn.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Shuaiby aslam",
    portada: "https://files.catbox.moe/cmckv4.png",
    video: "https://files.catbox.moe/rbp9vt.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Los amo padres",
    portada: "https://files.catbox.moe/8yug69.png",
    video: "https://files.catbox.moe/9huz9r.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "SE APUÑALA EN LIVE", //C-AUTOLESIONES
    portada: "https://files.catbox.moe/a5ey0v.png",
    video: "https://files.catbox.moe/ugfr18.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Se saca un cuchillo del estomago",
    portada: "https://files.catbox.moe/oh20og.png",
    video: "https://files.catbox.moe/vitjor.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "One man one jar",
    portada: "https://files.catbox.moe/vdkxb0.png",
    video: "https://files.catbox.moe/wq7b7b.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Se corta la mano",
    portada: "https://qu.ax/qJaSw.png",
    video: "https://files.catbox.moe/4r4b3t.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Amigos traicioneros",
    portada: "https://files.catbox.moe/t1umay.jpeg",
    video: "https://files.catbox.moe/l5khd1.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El roba cables 💀",
    portada: "https://files.catbox.moe/e43cws.png",
    video: "https://files.catbox.moe/p1m1k9.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
  },
];

// Exportar la base de datos
export default mediaDB;