
// Base de datos de videos
const mediaDB = [
  {
    id: "valeria-marquez",
    titulo: "Valeria Marquez", //C-ASESINATOS
    portada: "https://files.catbox.moe/slvfm7.png",
    video: "https://files.catbox.moe/1pkwcu.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "hdp-usa-el-cuerpo-de-su-amigo-como-escudo",
    titulo: "HDP usa el cuerpo de su amigo como escudo.",
    portada: "https://xxx.livegore.com//rb-include/videos/4641070840.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4641070840.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "en-el-show",
    titulo: "En el show",
    portada: "https://files.catbox.moe/dt5026.png",
    video: "https://files.catbox.moe/ubdh0r.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "lo-dejaron-como-lego",
    titulo: "Lo dejaron como lego",
    portada: "https://files.catbox.moe/td2vax.png",
    video: "https://files.catbox.moe/cqf1do.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "dj-en-la-discoteca",
    titulo: "Dj en la discoteca",
    portada: "https://files.catbox.moe/6x7mhl.png",
    video: "https://files.catbox.moe/6cj2ra.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "miss-pacman-version-hombre",
    titulo: "Miss pacman version hombre",
    portada: "https://files.catbox.moe/vo5diu.png",
    video: "https://files.catbox.moe/n9qhmw.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "dulces-suenos",
    titulo: "Dulces sueños",
    portada: "https://files.catbox.moe/dg3ekz.png",
    video: "https://qu.ax/eAhz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "ultra-sicariato",
    titulo: "Ultra sicariato",
    portada: "https://files.catbox.moe/oherqd.png",
    video: "https://files.catbox.moe/luaidc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "debora-bessa",
    titulo: "Debora Bessa",
    portada: "https://files.catbox.moe/7yjs4f.png",
    video: "https://files.catbox.moe/8kmz8o.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mejores-amigas",
    titulo: "Mejores amigas",
    portada: "https://files.catbox.moe/hsjdhw.png",
    video: "https://xxx.livegore.com//rb-include/videos/9147177832.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "ninos-acribillados",
    titulo: "Niños acribillados",
    portada: "https://files.catbox.moe/70o082.png",
    video: "https://xxx.livegore.com//rb-include/videos/2778559220.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "cabo-su-propia-tumba",
    titulo: "Cabo su propia tumba",
    portada: "https://files.catbox.moe/77wq57.png",
    video: "https://qu.ax/Xmxc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "terror-en-barberia",
    titulo: "Terror en barberia",
    portada: "https://files.catbox.moe/c15ytq.png",
    video: "https://xxx.livegore.com//rb-include/videos/9372303844.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "5-segundos-para-correr",
    titulo: "5 segundos para correr",
    portada: "https://files.catbox.moe/vxgssg.png",
    video: "https://files.catbox.moe/s1urbp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "el-patron",
    titulo: "El patron",
    portada: "https://files.catbox.moe/7fq07r.png",
    video: "https://files.catbox.moe/cyqbgr.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "negro-en-el-suelo",
    titulo: "Negro en el suelo",
    portada: "https://files.catbox.moe/5a6eui.png",
    video: "https://xxx.livegore.com//rb-include/videos/407954896.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "funky-town",
    titulo: "Funky Town",
    portada: "https://files.catbox.moe/wtk7g0.png",
    video: "https://files.catbox.moe/cwsb27.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "maria-fernanda-garcia-alvarez",
    titulo: "Maria Fernanda Garcia Alvarez",
    portada: "https://files.catbox.moe/cn2qfa.png",
    video: "https://files.catbox.moe/4vx4ux.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "chupetica-de-lengua",
    titulo: "Chupetica de lengua",
    portada: "https://files.catbox.moe/4nlmad.png",
    video: "https://files.catbox.moe/ayihdd.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "sicariato-veloz",
    titulo: "Sicariato veloz",
    portada: "https://files.catbox.moe/8ljidh.png",
    video: "https://files.catbox.moe/zw8fzc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mayengg03",
    titulo: "Mayengg03",
    portada: "https://files.catbox.moe/q3qhpd.png",
    video: "https://qu.ax/hfzq.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "pastor-e-hijas",
    titulo: "Pastor e hijas",
    portada: "https://files.catbox.moe/2kmklg.png",
    video: "https://files.catbox.moe/cwu6r1.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mujer-sin-cabeza",
    titulo: "Mujer sin cabeza",
    portada: "https://files.catbox.moe/biadgn.png",
    video: "https://files.catbox.moe/20lf4e.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mientras-tiene-sexo",
    titulo: "Mientras tiene sexo",
    portada: "https://files.catbox.moe/qzu2t5.png",
    video: "https://xxx.livegore.com//rb-include/videos/8401789665.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "el-siri",
    titulo: "El siri",
    portada: "https://files.catbox.moe/chsck2.png",
    video: "https://files.catbox.moe/atn1s6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "enganada",
    titulo: "Engañada",
    portada: "https://files.catbox.moe/dx6khw.png",
    video: "https://files.catbox.moe/idqeer.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "descuartizacion",
    titulo: "Descuartizacion",
    portada: "https://files.catbox.moe/045rwa.png",
    video: "https://xxx.livegore.com//rb-include/videos/7525534546.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "delincuente-es-quemado-vivo",
    titulo: "Delincuente es quemado vivo",
    portada: "https://files.catbox.moe/tiyz17.png",
    video: "https://files.catbox.moe/njpeeo.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "tiktok-in-jamaica",
    titulo: "Tiktok in Jamaica",
    portada: "https://files.catbox.moe/1fwu7h.png",
    video: "https://files.catbox.moe/ygc30v.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "13-mineros-de-pataz",
    titulo: "13 mineros de pataz",
    portada: "https://files.catbox.moe/jl3861.png",
    video: "https://qu.ax/wgbNz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "no-te-duermas-morena",
    titulo: "No te duermas morena",
    portada: "https://files.catbox.moe/q9a05t.png",
    video: "https://forogore.net/data/video/1/1122-ce27403355895b0ceff4cc07a171fc40.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "el-mejor-consejo",
    titulo: "El mejor consejo",
    portada: "https://files.catbox.moe/qt9lpe.png",
    video: "https://files.catbox.moe/ks3clp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "el-pantera",
    titulo: "El pantera",
    portada: "https://files.catbox.moe/74rniv.png",
    video: "https://files.catbox.moe/p3a643.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "miss-pacman",
    titulo: "Miss pacman",
    portada: "https://files.catbox.moe/ygjeay.png",
    video: "https://files.catbox.moe/z718ba.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "le-mutilan-la-cabeza",
    titulo: "Le mutilan la cabeza",
    portada: "https://files.catbox.moe/qsbobq.png",
    video: "https://files.catbox.moe/gozwd8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "por-territorio",
    titulo: "Por territorio",
    portada: "https://files.catbox.moe/ep3nbr.png",
    video: "https://files.catbox.moe/a8g01p.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "ataque-brutal",
    titulo: "Ataque brutal",
    portada: "https://files.catbox.moe/8sdfmp.png",
    video: "https://xxx.livegore.com//rb-include/videos/3171774074.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mangue937",
    titulo: "Mangue937",
    portada: "https://files.catbox.moe/x9qhwf.png",
    video: "https://files.catbox.moe/xjryj6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "ejecucion-con-machete",
    titulo: "Ejecucion con machete",
    portada: "https://files.catbox.moe/ogepdz.png",
    video: "https://files.catbox.moe/i2lva5.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "a-4-mujeres",
    titulo: "A 4 mujeres",
    portada: "https://files.catbox.moe/bba8b2.png",
    video: "https://files.catbox.moe/fdw9gg.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "cabeza-con-salsa-de-tomate",
    titulo: "Cabeza con salsa de tomate",
    portada: "https://files.catbox.moe/ne9kng.png",
    video: "https://files.catbox.moe/zywytv.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "sadico-en-la-banqueta",
    titulo: "Sadico en la banqueta",
    portada: "https://files.catbox.moe/7bn7wy.png",
    video: "https://files.catbox.moe/8i1yfc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "seicariato-hogar",
    titulo: "Seicariato hogar",
    portada: "https://files.catbox.moe/eau99x.png",
    video: "https://files.catbox.moe/p5hvn8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "solo-por-4-dolares",
    titulo: "Solo por 4 dolares",
    portada: "https://files.catbox.moe/kwrima.png",
    video: "https://files.catbox.moe/gxylxy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "no-me-pises-pa",
    titulo: "No me pises pa",
    portada: "https://files.catbox.moe/3v7rxj.png",
    video: "https://files.catbox.moe/kb4d6i.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "quiero-agua",
    titulo: "QUIERO AGUA",
    portada: "https://files.catbox.moe/a2cw3r.png",
    video: "https://files.catbox.moe/l2lz6q.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "canservero",
    titulo: "Canservero",
    portada: "https://files.catbox.moe/sxc6qs.png",
    video: "https://files.catbox.moe/tfs5ma.mp4?f10k",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "patrocinado-por-adidas",
    titulo: "Patrocinado por adidas",
    portada: "https://files.catbox.moe/8448vs.png",
    video: "https://xxx.livegore.com//rb-include/videos/3258454720.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "fuente-de-sangre",
    titulo: "Fuente de sangre",
    portada: "https://files.catbox.moe/zqbhpt.png",
    video: "https://xxx.livegore.com//rb-include/videos/933355526.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "la-matan-frente-a-su-hija",
    titulo: "La matan frente a su hija",
    portada: "https://files.catbox.moe/3j7e9r.png",
    video: "https://files.catbox.moe/xprhs6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "hiper-baleado",
    titulo: "Hiper baleado",
    portada: "https://files.catbox.moe/p9cgnn.png",
    video: "https://files.catbox.moe/s65u0t.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mascara-realista",
    titulo: "Mascara realista",
    portada: "https://files.catbox.moe/2ngo6p.png",
    video: "https://files.catbox.moe/pn0sa9.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "en-el-local",
    titulo: "En el local",
    portada: "https://files.catbox.moe/826idb.png",
    video: "https://files.catbox.moe/m92oqa.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "su-ultimo-bailde",
    titulo: "Su ultimo bailde",
    portada: "https://files.catbox.moe/tqqyhy.png",
    video: "https://video.wixstatic.com/video/031579_f812d4bbd85449ee988c082e5d2cd46c/480p/mp4/file.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "mejor-tirame-un-balazo",
    titulo: "Mejor tirame un balazo",
    portada: "https://files.catbox.moe/wqc55i.png",
    video: "https://qu.ax/cZtn.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "amor-de-madre",
    titulo: "Amor de madre",
    portada: "https://files.catbox.moe/fw81p5.png",
    video: "https://files.catbox.moe/kvwgkk.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "los-colgados",
    titulo: "Los colgados",
    portada: "https://files.catbox.moe/5vlzgh.png",
    video: "https://xxx.livegore.com//rb-include/videos/2843126645.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "canibalismo",
    titulo: "Canibalismo",
    portada: "https://files.catbox.moe/b15tvr.png",
    video: "https://xxx.livegore.com//rb-include/videos/5890161800.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "te-manda-saludos",
    titulo: "Te manda saludos",
    portada: "https://files.catbox.moe/qfew9j.png",
    video: "https://xxx.livegore.com//rb-include/videos/5660945787.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "nino-asesina-a-su-padre",
    titulo: "Niño asesina a su padre",
    portada: "https://files.catbox.moe/z61sbm.png",
    video: "https://files.catbox.moe/driisy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "lamentos-de-la-muerte",
    titulo: "Lamentos de la muerte",
    portada: "https://files.catbox.moe/6trze4.png",
    video: "https://xxx.livegore.com//rb-include/videos/7094055935.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "hombre-en-el-suelo",
    titulo: "Hombre en el suelo",
    portada: "https://files.catbox.moe/5u1opj.png",
    video: "https://files.catbox.moe/8jnb2u.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "29/05/25",
  },
  {
    id: "el-caso-de-kleber-vieira-",
    titulo: "El caso de kleber vieira 💀",
    portada: "https://files.catbox.moe/n40vtw.png",
    video: "https://files.catbox.moe/k95yws.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "30/05/25",
  },
  {
    id: "asesinado-sin-piedad-en-myanmar",
    titulo: "Asesinado sin piedad en Myanmar",
    portada: "https://xxx.livegore.com//rb-include/videos/5565926800.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5565926800.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "30/05/25",
  },
  {
    id: "no-mercy-in-mexico",
    titulo: "No mercy in Mexico",
    portada: "https://xxx.livegore.com//rb-include/videos/9235306940.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9235306940.mp4",
    autor: "falcolucas34552",
    categoria: "ASESINATOS",
    fecha: "30/05/25",
  },
  {
    id: "ghost-rider",
    titulo: "Ghost Rider",
    portada: "https://xxx.livegore.com//rb-include/videos/954456399.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/954456399.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "amigos-traicioneros",
    titulo: "Amigos traicioneros",
    portada: "https://files.catbox.moe/t1umay.jpeg",
    video: "https://files.catbox.moe/l5khd1.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "el-roba-cables-",
    titulo: "El roba cables 💀",
    portada: "https://files.catbox.moe/e43cws.png",
    video: "https://files.catbox.moe/p1m1k9.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "grupo-dragones",
    titulo: "Grupo Dragones",
    portada: "https://files.catbox.moe/xxz974.png",
    video: "https://web.mundonarco.com/H4M59mNGjM.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "mutilan-su-cuerpo",
    titulo: "Mutilan su cuerpo",
    portada: "https://xxx.livegore.com//rb-include/videos/6779993185.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6779993185.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "puro-4-letras",
    titulo: "Puro 4 letras",
    portada: "https://xxx.livegore.com//rb-include/videos/9377648192.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9377648192.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "pistola-y-machete",
    titulo: "Pistola y machete",
    portada: "https://xxx.livegore.com//rb-include/videos/7547958004.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7547958004.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "los-que-causa-una-escopeta",
    titulo: "Lo que causa una escopeta",
    portada: "https://xxx.livegore.com//rb-include/videos/6233442062.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6233442062.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "los-sicarios",
    titulo: "Los sicarios",
    portada: "https://xxx.livegore.com//rb-include/videos/4957052520.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4957052520.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "los-vikingos",
    titulo: "Los vikingos",
    portada: "https://xxx.livegore.com//rb-include/videos/8628896870.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8628896870.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "en-su-propia-casa",
    titulo: "En su propia casa",
    portada: "https://xxx.livegore.com//rb-include/videos/9221892952.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9221892952.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "sin-piedad-en-los-carteles",
    titulo: "Sin piedad en los carteles",
    portada: "https://xxx.livegore.com//rb-include/videos/2150121801.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2150121801.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "el-canibal-del-cjng",
    titulo: "El canibal del CJNG",
    portada: "https://xxx.livegore.com//rb-include/videos/8647406059.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8647406059.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "decapitados",
    titulo: "Decapitados",
    portada: "https://xxx.livegore.com//rb-include/videos/5348090138.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5348090138.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "31/05/25",
  },
  {
    id: "en-posicion-rugby",
    titulo: "En posicion Rugby",
    portada: "https://xxx.livegore.com//rb-include/videos/1428998378.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1428998378.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "no-pago-a-su-amo",
    titulo: "No pagó a su amo",
    portada: "https://xxx.livegore.com//rb-include/videos/4580946671.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4580946671.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "integrantes-de-la-ultima-letra-del-abecedario",
    titulo: "Los de la ultima letra del abecedario",
    portada: "https://xxx.livegore.com//rb-include/videos/7000574003.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7000574003.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "ojo-por-ojo",
    titulo: "Ojo por ojo",
    portada: "https://xxx.livegore.com//rb-include/videos/2833162536.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2833162536.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "no-mi-apa-porfavor",
    titulo: "No mi apa por favor",
    portada: "https://xxx.livegore.com//rb-include/videos/7277199048.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7277199048.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "dos-cabezas",
    titulo: "Dos cabezas",
    portada: "https://xxx.livegore.com//rb-include/videos/46152430.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/46152430.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "a-machetasos",
    titulo: "A machetasos",
    portada: "https://xxx.livegore.com//rb-include/videos/8677922221.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8677922221.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "comandante-z",
    titulo: "Comandante zet4",
    portada: "https://xxx.livegore.com//rb-include/videos/609056418.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/609056418.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "juan-carlos-santiago",
    titulo: "Juan Carlos Santiago",
    portada: "https://xxx.livegore.com//rb-include/videos/1345838746.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1345838746.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "1/06/25",
  },
  {
    id: "lo-torturan-con-machete",
    titulo: "Lo torturan con machete💀",
    portada: "https://files.catbox.moe/tayo3a.png",
    video: "https://files.catbox.moe/dydggv.mp4",
    autor: "falcolucas34552",
    categoria: "ASESINATOS",
    fecha: "2/06/25",
  },
  {
    id: "la-reina-del-arroz-con-pollo",
    titulo: "La reina del arroz con pollo",
    portada: "https://qu.ax/jrjHV.png",
    video: "https://forogore.net/data/video/123/123320-b45724c4b2764e0e81de4e2a5f13d1df.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
    fecha: "2/06/25",
  },
  {
    id: "el-exprimidor-humano",
    titulo: "El exprimidor humano",
    portada: "https://xxx.livegore.com//rb-include/videos/706962365.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/706962365.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "4/06/25",
  },
  {
    id: "por-la-espalda",
    titulo: "Por la espalda",
    portada: "https://xxx.livegore.com//rb-include/videos/982653247.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/982653247.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "4/06/25",
  },
  {
    id: "adolescente-pandillero",
    titulo: "Adolescente pandillero",
    portada: "https://xxx.livegore.com//rb-include/videos/2746584666.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2746584666.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "4/06/25",
  },
  {
    id: "gore-edit",
    titulo: "GORE EDIT",
    portada: "https://files.catbox.moe/nf79d9.jpg",
    video: "https://files.catbox.moe/gj41ma.mp4",
    autor: "mientrastambien509",
    categoria: "ASESINATOS",
    fecha: "11/06/25",
  },
  {
    id: "cabezas-compilacion",
    titulo: "Cabezas compilación",
    portada: "https://xxx.livegore.com//rb-include/videos/2084001116.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2084001116.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "cv-vs-tcp",
    titulo: "CV VS TCP",
    portada: "https://xxx.livegore.com//rb-include/videos/2385722114.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2385722114.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "pandilla-haitiana",
    titulo: "Pandilla Haitiana",
    portada: "https://xxx.livegore.com//rb-include/videos/3651016987.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3651016987.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "turista-en-brasil",
    titulo: "Turista en Brasil",
    portada: "https://xxx.livegore.com//rb-include/videos/6517588132.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6517588132.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "no-pago-el-bar",
    titulo: "No pagó el bar",
    portada: "https://xxx.livegore.com//rb-include/videos/1139712883.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1139712883.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "decapitado-trata-de-hablar",
    titulo: "Decapitado trata de hablar",
    portada: "https://xxx.livegore.com//rb-include/videos/6503734118.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6503734118.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "pandillero-decapitado",
    titulo: "Pandillero decapitado",
    portada: "https://xxx.livegore.com//rb-include/videos/8309301696.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8309301696.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "si-me-quedo",
    titulo: "Si me quedo",
    portada: "https://files.catbox.moe/qkz6lj.png",
    video: "https://files.catbox.moe/mb7s10.mp4",
    autor: "sicowendynglove",
    categoria: "ASESINATOS",
    fecha: "12/06/25",
  },
  {
    id: "apunalo-a-su-hermano-por-golpear-a-su-madre",
    titulo: "Apuñalo a su hermano por golpear a su madre",
    portada: "https://files.catbox.moe/5fsd0j.png",
    video: "https://files.catbox.moe/t0u4ij.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "lo-matan-luego-de-interrogarlo",
    titulo: "Lo matan luego de interrogarlo",
    portada: "https://theync.com/media/thumbs/6/8/4/c/d/85886684cdb95e4a64.mp4/85886684cdb95e4a64.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/c/d/684cdbdad60ad.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "que-buen-disfraz",
    titulo: "Que buen disfraz",
    portada: "https://theync.com/media/thumbs/6/8/4/b/8/85886684b8e687a118.mp4/85886684b8e687a118.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/b/8/684b8e92203c6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "otavio-jordao-da-silva-hombre-desarmable",
    titulo: "Otavio jordao da silva (hombre desarmable)",
    portada: "https://files.catbox.moe/xkbwoe.png",
    video: "https://toanthaydinh.com/wp-content/uploads/2024/09/otavio-jordao-da-silva-video.mp4",
    autor: "addydmimejoramigohola",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "lagos-del-moreno",
    titulo: "Lagos del moreno",
    portada: "https://xxx.livegore.com//rb-include/videos/471824132.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/471824132.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "los-saca-de-la-barberia-para-matarlo",
    titulo: "Lo saca de la barberia para matarlo",
    portada: "https://xxx.livegore.com//rb-include/videos/197232961.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/197232961.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "tan-solo-de-dos-machetazos",
    titulo: "Tan solo de dos machetazos",
    portada: "https://xxx.livegore.com//rb-include/videos/6132401512.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6132401512.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "compilacio-gore-5-minutos",
    titulo: "Compilacion gore 5 minutos",
    portada: "https://xxx.livegore.com//rb-include/videos/1400218913.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1400218913.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "mata-a-su-esposa-con-una-roca",
    titulo: "Mata a su esposa con una roca",
    portada: "https://xxx.livegore.com//rb-include/videos/7673579291.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7673579291.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "extrangulado-en-la-favela",
    titulo: "Extrangulado en la favela",
    portada: "https://xxx.livegore.com//rb-include/videos/2298321817.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2298321817.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "cartel-asesina-a-la-familia-de-su-rival",
    titulo: "Cartel asesina a la familia de su rival",
    portada: "https://xxx.livegore.com//rb-include/videos/5849002529.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5849002529.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "ejecutado-con-metralleta",
    titulo: "Ejecutado con metralleta",
    portada: "https://xxx.livegore.com//rb-include/videos/2090406203.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2090406203.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/26/25",
  },
  {
    id: "decapitacion-a-hijo-de-12-anos-de-un-narco",
    titulo: "Decapitacion de hijo de 12 años de un narco",
    portada: "https://xxx.livegore.com//rb-include/videos/5499508529.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5499508529.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "decapita-a-un-traficante",
    titulo: "Decapita a un traficante",
    portada: "https://xxx.livegore.com//rb-include/videos/1035710228.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1035710228.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "decapitaron-a-miembros-del-cjng",
    titulo: "Decapitaron a mienbros del cjng",
    portada: "https://xxx.livegore.com//rb-include/videos/8348965356.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8348965356.mp4",
    autor: "normnando256",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "la-chapiza-ejecuta-a-miembros-de-la-mayiza",
    titulo: "La chapiza ejecuta a miembros de la mayiza",
    portada: "https://xxx.livegore.com//rb-include/videos/8533151661.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8533151661.mp4",
    autor: "normnando256",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "grupo-los-z-en-accion",
    titulo: "Grupo los z en accion",
    portada: "https://xxx.livegore.com//rb-include/videos/9501183410.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9501183410.mp4",
    autor: "normnando256",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "el-hombre-lego",
    titulo: "El hombre lego",
    portada: "https://xxx.livegore.com//rb-include/videos/5132780978.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5132780978.mp4",
    autor: "normnando256",
    categoria: "ASESINATOS",
    fecha: "14/06/25",
  },
  {
    id: "dron-mata-a-soldado",
    titulo: "Dron mata a soldado",
    portada: "https://xxx.livegore.com//rb-include/videos/9287931788.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9287931788.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "17/06/2025",
  },
  {
    id: "se-durmio-y-ya-no-desperto",
    titulo: "Se durmio y ya no desperto",
    portada: "https://xxx.livegore.com//rb-include/videos/3575599407.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3575599407.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
    fecha: "17/06/2025",
  },
  {
    id: "santiago-rodrigues",
    titulo: "Santiago Rodrigues",
    portada: "https://files.catbox.moe/cdg6un.jpeg",
    video: "https://xxx.livegore.com//rb-include/videos/1027467572.mp4",
    autor: "julio2016oo11",
    categoria: "ASESINATOS",
    fecha: "18/06/2025",
  },
  {
    id: "se-cree-estaca",
    titulo: "Se cree estaca", //C-ACCIDENTES
    portada: "https://files.catbox.moe/5jjfjq.png",
    video: "https://files.catbox.moe/7wqsp0.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "ancon-ventanilla",
    titulo: "Ancon ventanilla",
    portada: "https://files.catbox.moe/s430k9.png",
    video: "https://files.catbox.moe/rk1089.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "accidente-de-trafico",
    titulo: "ACCIDENTE DE TRAFICO",
    portada: "https://files.catbox.moe/sc2hom.png",
    video: "https://files.catbox.moe/7w56bs.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "hombre-puzzle",
    titulo: "Hombre puzzle",
    portada: "https://files.catbox.moe/pkxj7i.png",
    video: "https://xxx.livegore.com//rb-include/videos/7139274366.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "obulia-sanchez",
    titulo: "Obulia Sanchez",
    portada: "https://files.catbox.moe/bznuaq.png",
    video: "https://xxx.livegore.com//rb-include/videos/1824291097.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "la-grua",
    titulo: "La grua",
    portada: "https://files.catbox.moe/ncn5dn.png",
    video: "https://files.catbox.moe/b2lw79.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "angelito-caido-del-cielo",
    titulo: "Angelito caído del cielo",
    portada: "https://files.catbox.moe/dtuj10.png",
    video: "https://files.catbox.moe/jdo3f8.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "arrastrado-por-camion",
    titulo: "Arrastrado por camion",
    portada: "https://files.catbox.moe/sbstuy.png",
    video: "https://files.catbox.moe/7rj3m0.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "a-todo-gas",
    titulo: "A todo gas!",
    portada: "https://qu.ax/MpJRG.png",
    video: "https://files.catbox.moe/26p9hv.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "la-division",
    titulo: "La division",
    portada: "https://qu.ax/tZdRP.png",
    video: "https://xxx.livegore.com//rb-include/videos/6121349534.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "extrano-piercing",
    titulo: "Extraño piercing",
    portada: "https://qu.ax/gdNBX.png",
    video: "https://files.catbox.moe/1kury2.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "policia-erido",
    titulo: "Policia erido",
    portada: "https://files.catbox.moe/ygeh1d.png",
    video: "https://files.catbox.moe/g5kv2o.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "volado",
    titulo: "Volado",
    portada: "https://files.catbox.moe/kxv2zu.png",
    video: "https://files.catbox.moe/3j1103.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "camion-asesino",
    titulo: "Camion asesino",
    portada: "https://files.catbox.moe/r61f3p.png",
    video: "https://files.catbox.moe/ggr14p.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "toro-bravo",
    titulo: "Toro bravo",
    portada: "https://xxx.livegore.com//rb-include/videos/8443405479.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8443405479.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "tropeson",
    titulo: "Tropeson",
    portada: "https://files.catbox.moe/knwbto.png",
    video: "https://files.catbox.moe/1504za.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-jugar-con-pirotecnicos",
    titulo: "Por jugar con pirotecnicos",
    portada: "https://files.catbox.moe/apxrh3.png",
    video: "https://files.catbox.moe/k8tikr.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "llanta-explosiva",
    titulo: "Llanta explosiva",
    portada: "https://files.catbox.moe/vyyg7y.png",
    video: "https://files.catbox.moe/l5lilh.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "se-la-comio-un-tiburon",
    titulo: "Se la comio un tiburon",
    portada: "https://files.catbox.moe/fp2gmm.png",
    video: "https://xxx.livegore.com//rb-include/videos/7960827075.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "piquero-se-parte-la-cara",
    titulo: "Piquero se parte la cara",
    portada: "https://xxx.livegore.com//rb-include/videos/3819082602.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3819082602.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "sin-la-otra-mitad",
    titulo: "Sin la otra mitad",
    portada: "https://xxx.livegore.com//rb-include/videos/781994792.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/781994792.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "de-un-septimo-piso",
    titulo: "De un septimo piso",
    portada: "https://xxx.livegore.com//rb-include/videos/9534542048.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9534542048.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-su-motocicleta",
    titulo: "Por su motocicleta",
    portada: "https://xxx.livegore.com//rb-include/videos/8176755355.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8176755355.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "mortal-en-la-piscina",
    titulo: "Mortal en la piscina",
    portada: "https://xxx.livegore.com//rb-include/videos/5860242261.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5860242261.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "llanta-explosiva-v2",
    titulo: "Llanta explosiva v2",
    portada: "https://xxx.livegore.com//rb-include/videos/966582973.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/966582973.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "el-ciclista",
    titulo: "El ciclista",
    portada: "https://xxx.livegore.com//rb-include/videos/5183715061.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5183715061.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "el-exparcido",
    titulo: "El exparcido",
    portada: "https://xxx.livegore.com//rb-include/videos/2560339090.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2560339090.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "un-tren-la-partio-en-dos",
    titulo: "Un tren la partio en dos",
    portada: "https://xxx.livegore.com//rb-include/videos/5603941124.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5603941124.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "compartio-sus-pensamientos-con-la-pista",
    titulo: "Compartio sus pensamientos con la pista",
    portada: "https://xxx.livegore.com//rb-include/videos/4338209447.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4338209447.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "hdpt-aplasta-a-un-nino",
    titulo: "HDP aplasta a un niño",
    portada: "https://xxx.livegore.com//rb-include/videos/834812573.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/834812573.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "carrucel-danado",
    titulo: "Carrucel dañado",
    portada: "https://xxx.livegore.com//rb-include/videos/1779330233.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1779330233.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "hiroshima",
    titulo: "Hiroshima",
    portada: "https://xxx.livegore.com//rb-include/videos/6348164929.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6348164929.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "atrapado-por-la-avalancha",
    titulo: "Atrapado por la avalancha",
    portada: "https://xxx.livegore.com//rb-include/videos/6459340639.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6459340639.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "en-el-gym",
    titulo: "En el gym",
    portada: "https://xxx.livegore.com//rb-include/videos/6807811656.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6807811656.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "volo-sus-extremidades",
    titulo: "Voló sus extremidades",
    portada: "https://xxx.livegore.com//rb-include/videos/3172080474.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3172080474.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "quedo-torcido",
    titulo: "Quedó torcido",
    portada: "https://xxx.livegore.com//rb-include/videos/8134005921.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8134005921.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "estrenando-motocicleta",
    titulo: "Estrenando motocicleta",
    portada: "https://theync.com/media/thumbs/6/8/4/c/8/2144354684c4e5a47170.mp4/2144354684c4e5a47170.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/c/8/684c8a63eaa7b.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "vuelo-171-en-india",
    titulo: "Vuelo 171 en India",
    portada: "https://theync.com/media/thumbs/6/8/4/a/e/689168684ae750e4367.mp4/689168684ae750e4367.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/a/e/684ae7b1d6e90.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "cotado-por-amitad",
    titulo: "Cortado por la mitad",
    portada: "https://theync.com/media/thumbs/6/8/4/8/a/1479616848a01ee9c9e.mp4/1479616848a01ee9c9e.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/8/a/6848a0927b825.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "tanto-peso-lo-mato-aplastado",
    titulo: "Tanto peso lo mato aplastado",
    portada: "https://theync.com/media/thumbs/6/8/4/8/c/858866848c40b2556d.mp4/858866848c40b2556d.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/8/c/6848c432760c9.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "niño-atravazado-por-bara-de-fierro",
    titulo: "Niño atravezado por bara de fierro",
    portada: "https://files.catbox.moe/i6ncms.png",
    video: "https://forogore.net/data/video/231/231759-17d05db2dadc9bc849b6a8876c67cad3.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "compilacion-de-maquinas-deboradoras",
    titulo: "Compilación de maquinas deboradoras",
    portada: "https://xxx.livegore.com//rb-include/videos/746785080.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/746785080.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "motociclista-perde-la-cabeza-por-un-coche",
    titulo: "Motociclista pierde la cabeza por un coche",
    portada: "https://xxx.livegore.com//rb-include/videos/7113179587.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7113179587.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "come-la-banqueta",
    titulo: "Come la banqueta", //C-INCIDENTES
    portada: "https://files.catbox.moe/q7pgoy.png",
    video: "https://files.catbox.moe/hkxzb0.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "le-corta-sus-partes",
    titulo: "Le corta sus partes",
    portada: "https://files.catbox.moe/mefoa3.png",
    video: "https://xxx.livegore.com//rb-include/videos/4989582831.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "las-catrinas",
    titulo: "Las catrinas",
    portada: "https://files.catbox.moe/8cnbih.png",
    video: "https://xxx.livegore.com//rb-include/videos/8017226406.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "el-frutero",
    titulo: "El frutero",
    portada: "https://files.catbox.moe/snwzh4.png",
    video: "https://files.catbox.moe/wlw7kh.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "pastor-linchado-por-violar-a-su-hija",
    titulo: "Pastor linchado por violar a su hija",
    portada: "https://files.catbox.moe/epr5aw.png",
    video: "https://files.catbox.moe/otbt2d.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "4-5-1-2-3",
    titulo: "4 5 1 2 3",
    portada: "https://files.catbox.moe/ypk7ct.png",
    video: "https://files.catbox.moe/v23g8i.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "gresca-de-mujeres",
    titulo: "Gresca de mujeres",
    portada: "https://files.catbox.moe/e80xzu.png",
    video: "https://files.catbox.moe/1307ww.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-bailar-con-su-marido",
    titulo: "Por bailar con su marido",
    portada: "https://files.catbox.moe/cohi27.png",
    video: "https://files.catbox.moe/il5khb.MP4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "la-billie-elish-rusa",
    titulo: "La Billie Elish rusa",
    portada: "https://files.catbox.moe/m2iajh.png",
    video: "https://xxx.livegore.com//rb-include/videos/2504827566.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-matar-a-su-bebe",
    titulo: "Por matar a su bebe",
    portada: "https://files.catbox.moe/qr6i83.png",
    video: "https://files.catbox.moe/cmwlib.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "le-amputan-la-oreja",
    titulo: "Le amputan la oreja",
    portada: "https://files.catbox.moe/46b6a5.png",
    video: "https://files.catbox.moe/8fyuoi.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-burlase-de-su-presentacion",
    titulo: "Por burlase de su presentacion",
    portada: "https://files.catbox.moe/eezeto.png",
    video: "https://files.catbox.moe/s9ce2t.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "el-futbolista",
    titulo: "El futbolista",
    portada: "https://files.catbox.moe/mwzi22.png",
    video: "https://files.catbox.moe/delldy.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "por-robar",
    titulo: "Por robar",
    portada: "https://files.catbox.moe/3as0kv.png",
    video: "https://files.catbox.moe/prhxt5.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "valiente",
    titulo: "Valiente",
    portada: "https://files.catbox.moe/ib1n6g.png",
    video: "https://xxx.livegore.com//rb-include/videos/3146881824.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "tremendo-golpe-de-chilenos",
    titulo: "tremendo golpe de chilenos ",
    portada: "https://files.catbox.moe/za8l90.png",
    video: "https://files.catbox.moe/7dm7ug.mp4",
    autor: "perritogore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "lo-machetearon-y-cortazon-la-mano",
    titulo: "Lo machetearon y cortazon la mano",
    portada: "https://files.catbox.moe/rl4qtc.png",
    video: "https://files.catbox.moe/r81nkv.mp4",
    autor: "perritogore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "no-le-robes-a-un-narco-mija",
    titulo: "No le robes a un narco mija",
    portada: "https://xxx.livegore.com//rb-include/videos/6842782353.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6842782353.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "los-vagos-12",
    titulo: "Los vagos 12",
    portada: "https://xxx.livegore.com//rb-include/videos/2281307470.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2281307470.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "martillazos-en-la-cabeza",
    titulo: "Martillazos en la cabeza",
    portada: "https://files.catbox.moe/fm3uku.png",
    video: "https://files.catbox.moe/cj1u5c.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "29/05/25",
  },
  {
    id: "canibalismo-copilation",
    titulo: "Copilacion de canibalismo",
    portada: "https://xxx.livegore.com//rb-include/videos/8647024347.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8647024347.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "canibalismo-in-haiti",
    titulo: "Canibalismo en Haiti",
    portada: "https://xxx.livegore.com//rb-include/videos/1160076954.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1160076954.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "abandonada",
    titulo: "Abandonada",
    portada: "https://files.catbox.moe/omz5gp.png",
    video: "https://theync.com/media/videos/6/8/3/a/5/683a5d024b626.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "intento-robarle-el-arma-a-un-oficial",
    titulo: "Intento robarle el arma a un oficial",
    portada: "https://files.catbox.moe/ah8r0r.png",
    video: "https://theync.com/media/videos/6/8/3/6/0/683600ae96c93.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "hombre-antorcha",
    titulo: "Hombre antorcha",
    portada: "https://xxx.livegore.com//rb-include/videos/6902202018.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6902202018.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "chicago-3r-mundo",
    titulo: "El tercer mundo en chicago",
    portada: "https://xxx.livegore.com//rb-include/videos/6009008642.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/6009008642.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "por-no-pagar-sus-deudas",
    titulo: "Por no pagar sus deudas",
    portada: "https://xxx.livegore.com//rb-include/videos/4094127509.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4094127509.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "no-se-juega-con-un-tigre",
    titulo: "No se juega con un tigre",
    portada: "https://xxx.livegore.com//rb-include/videos/5023679542.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5023679542.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "estudiantes-de-nigeria",
    titulo: "Estudiantes de Nigeria",
    portada: "https://xxx.livegore.com//rb-include/videos/624512778.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/624512778.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "31/05/25",
  },
  {
    id: "el-sin-cara",
    titulo: "El sin cara",
    portada: "https://xxx.livegore.com//rb-include/videos/5910428534.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5910428534.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "le-dan-una-buena-leccion",
    titulo: "Le dan una buena leccion",
    portada: "https://xxx.livegore.com//rb-include/videos/834268233.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/834268233.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "1/06/25",
  },
  {
    id: "se-acosto-con-la-persona-equivocada",
    titulo: "Se acostó con la persona equivocada",
    portada: "https://xxx.livegore.com//rb-include/videos/3209148435.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3209148435.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "quemada-por-infiel",
    titulo: "Quemada por infiel",
    portada: "https://xxx.livegore.com//rb-include/videos/5382124218.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5382124218.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "ucranianos-derrotados",
    titulo: "Ucranianos derrotados",
    portada: "https://xxx.livegore.com//rb-include/videos/5094244852.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5094244852.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "trenesito-trenesito",
    titulo: "Trenesito trenesito",
    portada: "https://xxx.livegore.com//rb-include/videos/4488875651.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4488875651.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "amputacion-de-dedo",
    titulo: "Amputación de dedo",
    portada: "https://xxx.livegore.com//rb-include/videos/131879909.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/131879909.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "12/06/25",
  },
  {
    id: "el-roncador",
    titulo: "El roncador",
    portada: "https://xxx.livegore.com//rb-include/videos/4747737660.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4747737660.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "13/06/25",
  },
  {
    id: "tortura-a-integrante-de-los-z",
    titulo: "Tortura a integrante de los z",
    portada: "https://xxx.livegore.com//rb-include/videos/1882996526.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1882996526.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "13/06/25",
  },
  {
    id: "ciencuenta-soldados-nigerianos-abatidos-por-milicia-fulani",
    titulo: "CINCUENTA SOLDADOS NIGERIANOS ABATIDOS POR MILICIA FULANI",
    portada: "https://theync.com/media/thumbs/6/8/4/b/9/689168684b90518d9cc.mp4/689168684b90518d9cc.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/b/9/684b93060a108.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "se-llevan-y-no-aguantan",
    titulo: "Se llevan y no aguantan",
    portada: "https://theync.com/media/thumbs/6/8/4/b/0/1928516684ae0930f4cb.mp4/1928516684ae0930f4cb.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/b/0/684b00a1b2f3e.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "policia-abate-a-delincuente",
    titulo: "Policia abate a delincuente",
    portada: "https://theync.com/media/thumbs/6/8/4/9/f/858866849f2adabb23.mp4/858866849f2adabb23.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/9/f/6849f2c5c8f64.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "gresca-de-estudiantes-en-nigeria",
    titulo: "Gresca de estudiantes en Nigeria",
    portada: "https://theync.com/media/thumbs/6/8/4/b/9/689168684b92f180c7b.mp4/689168684b92f180c7b.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/b/9/684b946e1d1cd.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "pareja-asesinada-en-su-coche",
    titulo: "Pareja-asesinada-en-su-coche",
    portada: "https://theync.com/media/thumbs/6/8/4/9/a/214435468494188451b4.mp4/214435468494188451b4.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/9/a/6849a56e66cb1.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "desertor-es-castigado",
    titulo: "Desertor es castigado",
    portada: "https://theync.com/media/thumbs/6/8/4/9/a/1190846684976f853ffd.mp4/1190846684976f853ffd.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/9/a/6849a72084a41.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "balacera-con-policias-en-chicago",
    titulo: "Balacera con policia en Chicago",
    portada: "https://theync.com/media/thumbs/6/8/4/a/0/85886684a007491bc5.mp4/85886684a007491bc5.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/a/0/684a00d6679cf.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "la-econtraron-sin-cabeza",
    titulo: "La encontraron sin cabeza",
    portada: "https://theync.com/media/thumbs/6/8/4/8/7/8588668487abe077b2.mp4/8588668487abe077b2.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/8/7/68487b4df1a0f.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "no-seas-presumido",
    titulo: "No seas presumido",
    portada: "https://theync.com/media/thumbs/6/8/4/8/5/6891686848577d488d3.mp4/6891686848577d488d3.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/8/5/68485a05bbb0e.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "ladron-es-torturado",
    titulo: "Ladron es torturado",
    portada: "https://files.catbox.moe/qb07dj.png",
    video: "https://forogore.net/data/video/240/240153-406e1fe0e55f374cd0b49692f392075e.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "lo-ataca-con-un-palo-en-la-cabeza",
    titulo: "Lo ataca con un palo en la cabeza",
    portada: "https://xxx.livegore.com//rb-include/videos/4876252706.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4876252706.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "castigando-a-un-violador",
    titulo: "Castigando a un violador",
    portada: "https://xxx.livegore.com//rb-include/videos/1427894476.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1427894476.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "le-corta-el-dedo-a-esta-mujer",
    titulo: "Le corta el dedo a esta mujer",
    portada: "https://xxx.livegore.com//rb-include/videos/9922446333.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9922446333.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "desmembrada-por-una-pandilla",
    titulo: "Desmembrada por una pandilla",
    portada: "https://xxx.livegore.com//rb-include/videos/2230310221.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2230310221.mp4",
    autor: "normnando256",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "mato-a-su-esposa-y-luego-se-suicido",
    titulo: "Mató a su esposa y luego se suicido",
    portada: "https://xxx.livegore.com//rb-include/videos/3846105993.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3846105993.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "puzzle-de-los-carteles",
    titulo: "Puzzle de los carteles",
    portada: "https://xxx.livegore.com//rb-include/videos/3618318075.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3618318075.mp4",
    autor: "normnando256",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "miembros-de-un-cartel-destrozan-el-cuerpo-de-su-rival",
    titulo: "Miembros de un cartel destrozan el cuerpo de su rival",
    portada: "https://xxx.livegore.com//rb-include/videos/3178778504.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3178778504.mp4",
    autor: "normnando256",
    categoria: "INCIDENTES",
    fecha: "14/06/25",
  },
  {
    id: "apunala-a-una-escocesa",
    titulo: "Apuñala a una Escocesa",
    portada: "https://xxx.livegore.com//rb-include/videos/7847417825.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7847417825.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "quiso-matar-a-un-policia",
    titulo: "Quiso matar a un policia",
    portada: "https://xxx.livegore.com//rb-include/videos/4788366840.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4788366840.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "lo-mandaron-a-dormir",
    titulo: "Lo mandaron a dormir",
    portada: "https://xxx.livegore.com//rb-include/videos/9865345698.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9865345698.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "policia-mata-a-esquizofrenico",
    titulo: "Policia mata a esquizofrenico",
    portada: "https://xxx.livegore.com//rb-include/videos/8203597120.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8203597120.mp4",
    autor: "normnando256",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "coche-atropella-a-anciano",
    titulo: "Acoche atropella a anciano",
    portada: "https://xxx.livegore.com//rb-include/videos/5386844566.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/5386844566.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "colombiano-muerto-afuera-de-bar",
    titulo: "Colombiano muerto afuera de Bar",
    portada: "https://xxx.livegore.com//rb-include/videos/2372484761.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2372484761.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "toro-se-desahogo-con-un-maldito",
    titulo: "Toro se desahogo con un maldito",
    portada: "https://xxx.livegore.com//rb-include/videos/735025755.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/735025755.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
    fecha: "17/06/2025",
  },
  {
    id: "1444",
    titulo: "1444", //C-SUICIDIOS
    portada: "https://xxx.livegore.com//rb-include/videos/8122189044.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8122189044.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "india-facebook",
    titulo: "India facebook",
    portada: "https://files.catbox.moe/pbnki8.png",
    video: "https://files.catbox.moe/nj8b9j.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "tres-de-la-manana-en-bolivia-",
    titulo: "TRES DE LA MAÑANA EN BOLIVIA 💀",
    portada: "https://files.catbox.moe/7j2w3h.jpg",
    video: "https://files.catbox.moe/j6lqov.mp4",
    autor: "desconocido777",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "mujer-saltando-de-su-apartamento-en-rusia",
    titulo: "Mujer Saltando De Su Apartamento En Rusia",
    portada: "https://xxx.livegore.com//rb-include/videos/4958379347.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4958379347.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "ultima-llamada",
    titulo: "Ultima llamada",
    portada: "https://files.catbox.moe/rx2a0o.png",
    video: "https://files.catbox.moe/jeggdn.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "shuaiby-aslam",
    titulo: "Shuaiby aslam",
    portada: "https://files.catbox.moe/cmckv4.png",
    video: "https://files.catbox.moe/rbp9vt.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "los-amo-padres",
    titulo: "Los amo padres",
    portada: "https://files.catbox.moe/8yug69.png",
    video: "https://files.catbox.moe/9huz9r.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "29/05/25",
  },
  {
    id: "idiota-se-tira-del-decimo-piso",
    titulo: "Idiota se tira del decimo piso",
    portada: "https://xxx.livegore.com//rb-include/videos/9326846785.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9326846785.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "31/05/25",
  },
  {
    id: "ronnie-mcnutt",
    titulo: "Ronnie Mcnutt",
    portada: "https://xxx.livegore.com//rb-include/videos/7125023552.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7125023552.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "1/06/25",
  },
  {
    id: "se-cuelga",
    titulo: "Se cuelga",
    portada: "https://xxx.livegore.com//rb-include/videos/7958023501.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7958023501.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "1/06/25",
  },
  {
    id: "suicidio-de-daniel-V-Jones",
    titulo: "Suicidio de Daniel V. Jones",
    portada: "https://xxx.livegore.com//rb-include/videos/2210086090.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/2210086090.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "12/06/25",
  },
  {
    id: "chinas-se-suicidaron",
    titulo: "Chinas se suicidaron",
    portada: "https://xxx.livegore.com//rb-include/videos/7738308603.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/7738308603.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "12/06/25",
  },
  {
    id: "youtuber-estupido",
    titulo: "Youtuber estupido",
    portada: "https://files.catbox.moe/1qxni1.png",
    video: "https://theync.com/media/videos/6/8/4/2/2/68422d675788e.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "12/06/25",
  },
  {
    id: "lo-obligaron-a-suicidarse",
    titulo: "Lo obligaron a suicidarse en prisión",
    portada: "https://xxx.livegore.com//rb-include/videos/9592857160.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/9592857160.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "14/06/25",
  },
  {
    id: "soldado-se-suicidia",
    titulo: "Soldado se suicida",
    portada: "https://xxx.livegore.com//rb-include/videos/1302137337.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/1302137337.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
    fecha: "17/06/2025",
  },
  {
    id: "se-apunala-en-live",
    titulo: "SE APUÑALA EN LIVE", //C-AUTOLESIONES
    portada: "https://files.catbox.moe/a5ey0v.png",
    video: "https://files.catbox.moe/ugfr18.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "29/05/25",
  },
  {
    id: "se-saca-un-cuchillo-del-estomago",
    titulo: "Se saca un cuchillo del estomago",
    portada: "https://files.catbox.moe/oh20og.png",
    video: "https://files.catbox.moe/vitjor.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "29/05/25",
  },
  {
    id: "one-man-one-jar",
    titulo: "One man one jar",
    portada: "https://files.catbox.moe/vdkxb0.png",
    video: "https://files.catbox.moe/wq7b7b.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "29/05/25",
  },
  {
    id: "se-corta-la-mano",
    titulo: "Se corta la mano",
    portada: "https://qu.ax/qJaSw.png",
    video: "https://files.catbox.moe/4r4b3t.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "29/05/25",
  },
  {
    id: "ladron-muere-electrocutado-por-sobar-cables",
    titulo: "Ladrón muere electrocutado por robar clables",
    portada: "https://xxx.livegore.com//rb-include/videos/4773093513.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4773093513.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "31/05/25",
  },
  {
    id: "estupida-se-prende-fuego-por-un-reto",
    titulo: "Estupida se prende fuego por un reto",
    portada: "https://files.catbox.moe/39q8o1.png",
    video: "https://theync.com/media/videos/6/8/4/8/4/68484d4609c3c.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "12/06/25",
  },
  {
    id: "imbecil-es-electrocutado",
    titulo: "Imbecil-es-electrocutado",
    portada: "https://theync.com/media/thumbs/6/8/4/5/f/13121946845ee08951d7.mp4/13121946845ee08951d7.mp4-9.jpg",
    video: "https://theync.com/media/videos/6/8/4/5/f/6845f43b37fad.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "14/06/25",
  },
  {
    id: "se-prenden-fuego-jugando",
    titulo: "Se prenden fuego jugando",
    portada: "https://theync.com/media/thumbs/6/8/4/9/8/11704826849827e48cd3.mp4/11704826849827e48cd3.mp4-3.jpg",
    video: "https://theync.com/media/videos/6/8/4/9/8/684982be51c28.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
    fecha: "14/06/25",
  },
];

// Exportar la base de datos
export default mediaDB;
