// Base de datos de videos
const mediaDB = [
  {
    titulo: "Los amo padres",
    portada: "https://files.catbox.moe/8yug69.png",
    video: "https://files.catbox.moe/9huz9r.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Valeria Marquez",
    portada: "https://files.catbox.moe/slvfm7.png",
    video: "https://files.catbox.moe/1pkwcu.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "HDP usa el cuerpo de su amigo como escudo.",
    portada: "https://xxx.livegore.com//rb-include/videos/4641070840.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/4641070840.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "En el show",
    portada: "https://files.catbox.moe/dt5026.png",
    video: "https://files.catbox.moe/ubdh0r.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Lo dejaron como lego",
    portada: "https://nostgore.xyz/imagenes/lodejaroncomolego.png",
    video: "https://files.catbox.moe/cqf1do.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Dj en la discoteca",
    portada: "https://nostgore.xyz/imagenes/asesinatodedj.png",
    video: "https://files.catbox.moe/6cj2ra.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Miss pacman version hombre",
    portada: "https://nostgore.xyz/imagenes/misspacmanversionhombre.png",
    video: "https://files.catbox.moe/n9qhmw.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Dulces sueños",
    portada: "https://files.catbox.moe/dg3ekz.png",
    video: "https://qu.ax/eAhz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Se cree estaca",
    portada: "https://nostgore.xyz/imagenes/hombreestaca.png",
    video: "https://files.catbox.moe/7wqsp0.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Martillazos en la cabeza",
    portada: "https://nostgore.xyz/imagenes/martillasosenacabeza.png",
    video: "https://files.catbox.moe/cj1u5c.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES, ASESINATOS",
  },
  {
    titulo: "Ultra sicariato",
    portada: "https://files.catbox.moe/oherqd.png",
    video: "https://files.catbox.moe/luaidc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Debora Bessa",
    portada: "https://nostgore.xyz/imagenes/Deborabessa.png",
    video: "https://files.catbox.moe/8kmz8o.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mejores amigas",
    portada: "https://nostgore.xyz/imagenes/mejoresamigas.png",
    video: "https://xxx.livegore.com//rb-include/videos/9147177832.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Shuaiby aslam",
    portada: "https://files.catbox.moe/cmckv4.png",
    video: "https://files.catbox.moe/rbp9vt.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Niños acribillados",
    portada: "https://nostgore.xyz/imagenes/ni%C3%B1osacribillados.png",
    video: "https://xxx.livegore.com//rb-include/videos/2778559220.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Cabo su propia tumba",
    portada: "https://files.catbox.moe/77wq57.png",
    video: "https://qu.ax/Xmxc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Come la banqueta",
    portada: "https://files.catbox.moe/q7pgoy.png",
    video: "https://files.catbox.moe/hkxzb0.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Ancon ventanilla",
    portada: "https://nostgore.xyz/imagenes/anconventanilla.png",
    video: "https://files.catbox.moe/rk1089.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "SE APUÑALA EN LIVE",
    portada: "https://nostgore.xyz/imagenes/seapu%C3%B1alaenlive.png",
    video: "https://files.catbox.moe/ugfr18.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Terror en barberia",
    portada: "https://files.catbox.moe/c15ytq.png",
    video: "https://xxx.livegore.com//rb-include/videos/9372303844.mp4",
    autor: "TripGore",
    categoria: "ASESINADOS",
  },
  {
    titulo: "ACCIDENTE DE TRAFICO",
    portada: "https://nostgore.xyz/imagenes/accidentedetrafico.png",
    video: "https://files.catbox.moe/7w56bs.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "5 segundos para correr",
    portada: "https://files.catbox.moe/vxgssg.png",
    video: "https://files.catbox.moe/s1urbp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Le corta sus partes",
    portada: "https://nostgore.xyz/imagenes/lecortansuspartes.png",
    video: "https://xxx.livegore.com//rb-include/videos/4989582831.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "El patron",
    portada: "https://nostgore.xyz/imagenes/elpatron.png",
    video: "https://files.catbox.moe/cyqbgr.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Negro en el suelo",
    portada: "https://nostgore.xyz/imagenes/niggaenapuros.png",
    video: "https://xxx.livegore.com//rb-include/videos/407954896.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Funky Town",
    portada: "https://nostgore.xyz/imagenes/funkytown.png",
    video: "https://files.catbox.moe/cwsb27.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Hombre puzzle",
    portada: "https://nostgore.xyz/imagenes/hombrepuzzle.png",
    video: "https://xxx.livegore.com//rb-include/videos/7139274366.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Obulia Sanchez",
    portada: "https://nostgore.xyz/imagenes/ObuliaSanchez.png",
    video: "https://xxx.livegore.com//rb-include/videos/1824291097.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Maria Fernanda Garcia Alvarez",
    portada: "https://nostgore.xyz/imagenes/mariagarciaalvares.png",
    video: "https://files.catbox.moe/4vx4ux.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "",
    portada: "",
    video: "",
    autor: "TripGore",
    categoria: "",
  },
  {
    titulo: "Chupetica de lengua",
    portada: "https://nostgore.xyz/imagenes/chupetedelengua.png",
    video: "https://files.catbox.moe/ayihdd.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Sicariato veloz",
    portada: "https://files.catbox.moe/8ljidh.png",
    video: "https://files.catbox.moe/zw8fzc.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mayengg03",
    portada: "https://nostgore.xyz/imagenes/mayengg03.png",
    video: "https://qu.ax/hfzq.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Se saca un cuchillo del estomago",
    portada: "https://files.catbox.moe/oh20og.png",
    video: "https://files.catbox.moe/vitjor.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Las catrinas",
    portada: "https://files.catbox.moe/8cnbih.png",
    video: "https://xxx.livegore.com//rb-include/videos/8017226406.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Pastor e hijas",
    portada: "https://nostgore.xyz/imagenes/pastorehijas.png",
    video: "https://files.catbox.moe/cwu6r1.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mujer sin cabeza",
    portada: "https://nostgore.xyz/imagenes/mujersincabeza.png",
    video: "https://files.catbox.moe/20lf4e.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mientras tiene sexo",
    portada: "https://nostgore.xyz/imagenes/apu%C3%B1aladamientrastienesexo.png",
    video: "https://xxx.livegore.com//rb-include/videos/8401789665.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Se corta la mano",
    portada: "https://nostgore.xyz/imagenes/semochalamano.png",
    video: "https://files.catbox.moe/4r4b3t.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "La grua",
    portada: "https://nostgore.xyz/imagenes/gruaenlacabeza.png",
    video: "https://files.catbox.moe/b2lw79.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Angelito caído del cielo",
    portada: "https://files.catbox.moe/dtuj10.png",
    video: "https://files.catbox.moe/jdo3f8.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "El siri",
    portada: "https://nostgore.xyz/imagenes/elsiri.png",
    video: "https://files.catbox.moe/atn1s6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El frutero",
    portada: "https://nostgore.xyz/imagenes/elfrutero.png",
    video: "https://files.catbox.moe/wlw7kh.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Arrastrado por camion",
    portada: "https://nostgore.xyz/imagenes/hombreneumatico.png",
    video: "https://files.catbox.moe/7rj3m0.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Engañada",
    portada: "https://nostgore.xyz/imagenes/escopetaycabeza.png",
    video: "https://files.catbox.moe/idqeer.MP4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Descuartizacion",
    portada: "https://nostgore.xyz/imagenes/lesacanelcorazon.png",
    video: "https://xxx.livegore.com//rb-include/videos/7525534546.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "A todo gas!",
    portada: "https://nostgore.xyz/imagenes/turbotactico.png",
    video: "https://files.catbox.moe/26p9hv.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES, AUTOLESIONES",
  },
  {
    titulo: "Pastor linchado por violar a su hija",
    portada: "https://files.catbox.moe/epr5aw.png",
    video: "https://files.catbox.moe/otbt2d.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Delincuente es quemado vivo",
    portada: "https://files.catbox.moe/tiyz17.png",
    video: "https://files.catbox.moe/njpeeo.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES, ASESINATOS",
  },
  {
    titulo: "Tiktok in Jamaica",
    portada: "https://nostgore.xyz/imagenes/tiktokinjamaica.png",
    video: "https://files.catbox.moe/ygc30v.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, INCIDENTES",
  },
  {
    titulo: "13 mineros de pataz",
    portada: "https://files.catbox.moe/jl3861.png",
    video: "https://qu.ax/wgbNz.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "No te duermas morena",
    portada: "https://files.catbox.moe/q9a05t.png",
    video: "https://forogore.net/data/video/1/1122-ce27403355895b0ceff4cc07a171fc40.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El mejor consejo",
    portada: "https://nostgore.xyz/imagenes/elmejorconsejo.png",
    video: "https://files.catbox.moe/ks3clp.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El pantera",
    portada: "https://nostgore.xyz/imagenes/elpantera.png",
    video: "https://files.catbox.moe/p3a643.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, INCIDENTES",
  },
  {
    titulo: "Miss pacman",
    portada: "https://nostgore.xyz/imagenes/misspacman.png",
    video: "https://files.catbox.moe/z718ba.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, INCIDENTES",
  },
  {
    titulo: "Le mutilan la cabeza",
    portada: "https://nostgore.xyz/imagenes/mutilaciondecabeza.png",
    video: "https://files.catbox.moe/gozwd8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "4 5 1 2 3",
    portada: "https://nostgore.xyz/imagenes/45123.png",
    video: "https://files.catbox.moe/v23g8i.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por territorio",
    portada: "https://nostgore.xyz/imagenes/balaceadoporterritorio.png",
    video: "https://files.catbox.moe/a8g01p.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ataque brutal",
    portada: "https://nostgore.xyz/imagenes/misspacmanextremoversionhombre.png",
    video: "https://xxx.livegore.com//rb-include/videos/3171774074.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mangue937",
    portada: "https://nostgore.xyz/imagenes/mangue37.png",
    video: "https://files.catbox.moe/xjryj6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Ejecucion con machete",
    portada: "https://nostgore.xyz/imagenes/ejecucionconmachete.png",
    video: "https://files.catbox.moe/i2lva5.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "A 4 mujeres",
    portada: "https://nostgore.xyz/imagenes/matana4mujeres.png",
    video: "https://files.catbox.moe/fdw9gg.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Cabeza con salsa de tomate",
    portada: "https://nostgore.xyz/imagenes/cabezaconsalsadetomate.png",
    video: "https://files.catbox.moe/zywytv.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "La division",
    portada: "https://nostgore.xyz/imagenes/misspacmanextremo.png",
    video: "https://xxx.livegore.com//rb-include/videos/6121349534.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Sadico en la banqueta",
    portada: "https://nostgore.xyz/imagenes/apu%C3%B1aladoenlabanqueta.png",
    video: "https://files.catbox.moe/8i1yfc.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES, ASESINATOS",
  },
  {
    titulo: "Extraño piercing",
    portada: "https://nostgore.xyz/imagenes/piercongextremo.png",
    video: "https://files.catbox.moe/1kury2.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Policia erido",
    portada: "https://nostgore.xyz/imagenes/policiaseriros.png",
    video: "https://files.catbox.moe/g5kv2o.MP4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Gresca de mujeres",
    portada: "https://nostgore.xyz/imagenes/grescademujeres.png",
    video: "https://files.catbox.moe/1307ww.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Volado",
    portada: "https://nostgore.xyz/imagenes/elgatovoladorversionhumano.png",
    video: "https://files.catbox.moe/3j1103.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES, ACCIDENTES",
  },
  {
    titulo: "Sicariato hogar",
    portada: "https://nostgore.xyz/imagenes/asesinatoencasa.png",
    video: "https://files.catbox.moe/p5hvn8.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Solo por 4 dolares",
    portada: "https://nostgore.xyz/imagenes/solopor4dolares.png",
    video: "https://files.catbox.moe/gxylxy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, INCIDENTES",
  },
  {
    titulo: "Por bailar con su marido",
    portada: "https://nostgore.xyz/imagenes/porbailarconsumarido.png",
    video: "https://files.catbox.moe/il5khb.MP4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "No me pises pa",
    portada: "https://nostgore.xyz/imagenes/nomepisespa.png",
    video: "https://files.catbox.moe/kb4d6i.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "QUIERO AGUA",
    portada: "https://nostgore.xyz/imagenes/quieroagua.png",
    video: "https://files.catbox.moe/l2lz6q.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Canservero",
    portada: "https://nostgore.xyz/imagenes/canserveromuerto.png",
    video: "https://files.catbox.moe/tfs5ma.mp4?f10k",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Patrocinado por adidas",
    portada: "https://nostgore.xyz/imagenes/patrocinadiporadidas.png",
    video: "https://xxx.livegore.com//rb-include/videos/3258454720.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "One man one jar",
    portada: "https://nostgore.xyz/imagenes/onemanonejar.png",
    video: "https://files.catbox.moe/wq7b7b.mp4",
    autor: "TripGore",
    categoria: "AUTOLESIONES",
  },
  {
    titulo: "Fuente de sangre",
    portada: "https://nostgore.xyz/imagenes/fuentedesangre.png",
    video: "https://xxx.livegore.com//rb-include/videos/933355526.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "La Billie Elish rusa",
    portada: "https://nostgore.xyz/imagenes/labillieelisgrusa.png",
    video: "https://xxx.livegore.com//rb-include/videos/2504827566.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "La matan frente a su hija",
    portada: "https://nostgore.xyz/imagenes/lamatanfrenteasuhija.png",
    video: "https://files.catbox.moe/xprhs6.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Hiper baleado",
    portada: "https://nostgore.xyz/imagenes/muertebaleado.png",
    video: "https://files.catbox.moe/s65u0t.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Por matar a su bebe",
    portada: "https://nostgore.xyz/imagenes/pormatarasubebe.png",
    video: "https://files.catbox.moe/cmwlib.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Ultima llamada",
    portada: "https://nostgore.xyz/imagenes/ultimallamada.png",
    video: "https://files.catbox.moe/jeggdn.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Camion asesino",
    portada: "https://nostgore.xyz/imagenes/camionasesino.png",
    video: "https://files.catbox.moe/ggr14p.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Le amputan la oreja",
    portada: "https://nostgore.xyz/imagenes/lecortanlaoreja.png",
    video: "https://files.catbox.moe/8fyuoi.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Mascara realista",
    portada: "https://nostgore.xyz/imagenes/mascararealizta.png",
    video: "https://files.catbox.moe/pn0sa9.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "En el local",
    portada: "https://nostgore.xyz/imagenes/masacreenlocal.png",
    video: "https://files.catbox.moe/m92oqa.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Toro bravo",
    portada: "https://xxx.livegore.com//rb-include/videos/8443405479.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/8443405479.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Su ultimo bailde",
    portada: "https://files.catbox.moe/tqqyhy.png",
    video: "https://video.wixstatic.com/video/031579_f812d4bbd85449ee988c082e5d2cd46c/480p/mp4/file.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Mejor tirame un balazo",
    portada: "https://files.catbox.moe/wqc55i.png",
    video: "https://qu.ax/cZtn.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Amor de madre",
    portada: "https://files.catbox.moe/fw81p5.png",
    video: "https://files.catbox.moe/kvwgkk.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, INCIDENTES",
  },
  {
    titulo: "Por burlase de su presentacion",
    portada: "https://files.catbox.moe/eezeto.png",
    video: "https://files.catbox.moe/s9ce2t.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "India facebook",
    portada: "https://files.catbox.moe/pbnki8.png",
    video: "https://files.catbox.moe/nj8b9j.mp4",
    autor: "TripGore",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "Los colgados",
    portada: "https://files.catbox.moe/5vlzgh.png",
    video: "https://xxx.livegore.com//rb-include/videos/2843126645.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "El futbolista",
    portada: "https://files.catbox.moe/mwzi22.png",
    video: "https://files.catbox.moe/delldy.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Por robar",
    portada: "https://files.catbox.moe/3as0kv.png",
    video: "https://files.catbox.moe/prhxt5.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Tropeson",
    portada: "https://files.catbox.moe/knwbto.png",
    video: "https://files.catbox.moe/1504za.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Canibalismo",
    portada: "https://nostgore.xyz/imagenes/canibalismo.png",
    video: "https://xxx.livegore.com//rb-include/videos/5890161800.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Te manda saludos",
    portada: "https://nostgore.xyz/imagenes/temandasaludos.png",
    video: "https://xxx.livegore.com//rb-include/videos/5660945787.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Por jugar con pirotecnicos",
    portada: "https://nostgore.xyz/imagenes/ni%C3%B1osinmanoperu.png",
    video: "https://files.catbox.moe/k8tikr.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Llanta explosiva",
    portada: "https://files.catbox.moe/vyyg7y.png",
    video: "https://files.catbox.moe/l5lilh.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Valiente",
    portada: "https://files.catbox.moe/ib1n6g.png",
    video: "https://xxx.livegore.com//rb-include/videos/3146881824.mp4",
    autor: "TripGore",
    categoria: "INCIDENTES",
  },
  {
    titulo: "Niño asesina a su padre",
    portada: "https://nostgore.xyz/imagenes/ni%C3%B1oasesinaasupadre.png",
    video: "https://files.catbox.moe/driisy.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS, ACCIDENTES",
  },
  {
    titulo: "Lamentos de la muerte",
    portada: "https://nostgore.xyz/imagenes/lamentosdelamuerte.png",
    video: "https://xxx.livegore.com//rb-include/videos/7094055935.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Hombre en el suelo",
    portada: "https://nostgore.xyz/imagenes/hombreenelsuelo.png",
    video: "https://files.catbox.moe/8jnb2u.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "Se la comio un tiburo",
    portada: "https://nostgore.xyz/imagenes/comidaporuntiburon.png",
    video: "https://xxx.livegore.com//rb-include/videos/7960827075.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES",
  },
  {
    titulo: "Piquero se parte la cara",
    portada: "https://xxx.livegore.com//rb-include/videos/3819082602.jpg",
    video: "https://xxx.livegore.com//rb-include/videos/3819082602.mp4",
    autor: "TripGore",
    categoria: "ACCIDENTES, AUTOLESIONES",
  },
  {
    titulo: "El caso de kleber vieira 💀",
    portada: "https://files.catbox.moe/n40vtw.png",
    video: "https://files.catbox.moe/k95yws.mp4",
    autor: "TripGore",
    categoria: "ASESINATOS",
  },
  {
    titulo: "tremendo golpe de chilenos ",
    portada: "https://files.catbox.moe/za8l90.png",
    video: "https://files.catbox.moe/7dm7ug.mp4",
    autor: "perritogore",
    categoria: "CONFLICTOS",
  },
  {
    titulo: "Lo machetearon y cortazon la mano",
    portada: "https://files.catbox.moe/rl4qtc.png",
    video: "https://files.catbox.moe/r81nkv.mp4",
    autor: "perritogore",
    categoria: "CONFLICTOS",
  },
  {
    titulo: "TRES DE LA MAÑANA EN BOLIVIA 💀",
    portada: "https://files.catbox.moe/7j2w3h.jpg",
    video: "https://files.catbox.moe/j6lqov.mp4",
    autor: "desconocido777",
    categoria: "SUICIDIOS",
  },
  {
    titulo: "",
    portada: "",
    video: "",
    autor: "TripGore",
    categoria: "",
  },
  {
    titulo: "",
    portada: "",
    video: "",
    autor: "TripGore",
    categoria: "",
  },
  {
    titulo: "",
    portada: "",
    video: "",
    autor: "TripGore",
    categoria: "",
  },
  {
    titulo: "",
    portada: "",
    video: "",
    autor: "TripGore",
    categoria: "",
  },
];

// Exportar la base de datos
export default mediaDB;
